source 'https://rubygems.org'

gem 'rack', '1.5.2'
gem 'sinatra'
gem 'liquid', github: 'urbandictionary/liquid', branch: 'missing_variables_and_filters'
gem 'rerun'
gem 'sass'
gem 'rspec'
gem 'rspec-html-matchers'
gem 'awesome_print'