source 'https://rubygems.org'

gem 'rack', '1.5.2'
gem 'sinatra'
gem 'liquid', github: 'Shopify/liquid'
gem 'rerun'
gem 'sass'
gem 'rspec'
gem 'rspec-html-matchers'
gem 'awesome_print'
gem 'activesupport'
gem 'rack-livereload'