---
settings:
  base_font_size: 12px
  background_color: white
  text_color: black
  link_color: blue
  base_font_family: Arial
  use_logo: false
  facebook_url: http://example.com/
  twitter_url: http://example.com/
  pinterest_url: http://example.com/
  googleplus_url: http://example.com/
  instagram_url: http://example.com/
  linkedin_url: http://example.com/
  flickr_url: http://example.com/
  yelp_url: http://example.com/
  vimeo_url: http://example.com/
  youtube_url: http://example.com/
  tumblr_url: http://example.com/
  wordpress_url: http://example.com/
  featured_blog: http://example.com/
  twittercard_handle: twittercard_handle
  social_icons_style: ""
  contact_email: "me@example.com"